version: '3.9'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: 'centribal-api'
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 5
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      makemigration:
        condition: service_completed_successfully
      migrate:
        condition: service_completed_successfully
  makemigration:
    build: .
    command: python manage.py makemigrations 
    volumes:
      - .:/code
    depends_on:
      db:
        condition: service_healthy
  
  migrate:
    build: .
    command: python manage.py migrate
    volumes:
      - .:/code 
    depends_on:
      makemigration:
        condition: service_completed_successfully
